### ISSUE TITLE
Team page broken 

### ISSUE THREAD

**Issue by joepio** [ontola/legalsafetlylab#12]
- Only 2 of 3 people
- No text for Jose 

<img width="1079" alt="Screenshot 2024-12-18 at 17 32 42" src="https://github.com/user-attachments/assets/df366c35-27bb-4d45-b745-e8f09d610491" />

**Comment by joepio** [comment]
Hmm, i updated the data and now I see three images, but only 2 texts. @Polleps can you find out what happens?

<img width="1092" alt="Screenshot 2024-12-19 at 10 06 56" src="https://github.com/user-attachments/assets/10365a63-2c5a-4877-aac7-469a0756a661" />

**Comment by joepio** [comment]
And now I see this one again! Is this caching + some last text issue?

<img width="1246" alt="Screenshot 2024-12-19 at 10 09 19" src="https://github.com/user-attachments/assets/48e0f6af-3023-47a6-9cc1-c236a182da2d" />

**Comment by Polleps** [comment]
> And now I see this one again! Is this caching + some last text issue?

There was an error. It tried to run .map on the supervisory board array which didn't exist anymore. I think in production when an error is encountered it just responds with whatever it has rendered until the error. So sometimes you got two team members and other times three.

**Comment by joepio** [comment]
Hmmm IMO that indicates we need to deal with errors in a different way. Shouldn't compile if there's a render block
